# Wlan Configuration
WLAN_CHIP_ID := $(patsubst %m,%,$(patsubst mt%,%,$(patsubst MT%,%,$(strip $(MTK_PLATFORM)))))
PRODUCT_PACKAGES += WIFI_RAM_CODE_$(WLAN_CHIP_ID)
PRODUCT_PACKAGES += WIFI_RAM_CODE_$(MTK_COMBO_CHIP)
PRODUCT_PACKAGES += WIFI_RAM_CODE_SOC
PRODUCT_PACKAGES += WIFI_RAM_CODE_AD
